name: CI

on:
  push:
    branches: main
  pull_request:
  workflow_call:  # allow this workflow to be called from other workflows

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - run: ./mill __.test
